export default [
    {
        cover: require('./covers/see.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '看见',
        nameEn: 'See',
        type: '电视剧',
        tags: ['科幻', '动作', '冷兵器'],
        duration: '50 分钟（单集）',
        premiere: '2019/11/01 - 2021/08/27',
        downloadLink: [
            {name: '第一季（8集）', downloadLink: 'https://www.meijutt.tv/content/meiju24907.html'},
            {name: '第二季（8集）', downloadLink: 'https://www.meijutt.tv/content/meiju26478.html'},
        ],
        language: '英语',
        actors: ['杰森·莫玛（DC海王）', '阿尔法·伍达德', '西尔维娅·侯克斯'],
        doubanLink: 'https://movie.douban.com/subject/27663210/',
        comment: '赞，拍摄，剪辑，故事，背景都很棒，近距离拍摄主角打斗很棒。'
    },
    {
        cover: require('./covers/the-next-three-days.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '危情三日',
        nameEn: 'The Next Three Days',
        type: '电影',
        tags: ['剧情', '情感'],
        duration: '133 分钟',
        premiere: '2011-04-29',
        downloadLink: [
            {name: '电影天堂', downloadLink: 'https://www.dy2018.com/html/gndy/jddyy/20110223/31017.html'},
        ],
        language: '英语',
        actors: ['罗素·克劳' , '伊丽莎白·班克斯' , '泰·辛普金斯' , '奥利维亚·王尔德' , '连姆·尼森' ],
        doubanLink: 'https://movie.douban.com/subject/3808604/',
        comment: '最喜欢的电影之一，里面的情感深深触动我'
    },
    {
        cover: require('./covers/knives-out.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '利刃出鞘',
        nameEn: 'Knives Out',
        type: '电影',
        tags: ['悬疑', '剧情'],
        duration: '130 分钟',
        premiere: '2019-11-29',
        downloadLink: [
            {name: '阳光电影1080p', downloadLink: 'https://www.ygdy8.com/html/gndy/china/20200209/59692.html'},
        ],
        language: '英语',
        actors: ['丹尼尔·克雷格' , '安娜·德·阿玛斯' , '克里斯·埃文斯' , '杰米·李·柯蒂斯' , '迈克尔·珊农'],
        doubanLink: 'https://movie.douban.com/subject/30318116/',
        comment: '刚开始人物比较多，需要消化一下，越看越精神，剧情NB。好看！'
    },
    {
        cover: require('./covers/the-time-travelers-wife.jpg'),
        wordTheme: 'white',
        position: 'right',
        name: '时间旅行者的妻子',
        nameEn: "The Time Traveler's Wife",
        type: '电影',
        tags: ['爱情', '奇幻'],
        duration: '107 分钟',
        premiere: '2009-08-14',
        downloadLink: [
            {name: '电影天堂', downloadLink: 'https://www.dy2018.com/i/99450.html'},
        ],
        language: '英语',
        actors: ['瑞秋·麦克亚当斯' , '艾瑞克·巴纳' , '阿莱克斯·费瑞斯' , '艾利斯·霍华德' , '米歇尔·诺尔顿'],
        doubanLink: 'https://movie.douban.com/subject/1885124/',
        comment: '看过很久很久了，最喜欢的电影之一，电影制作好。'
    },
    {
        cover: require('./covers/predestination.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '前目的地',
        nameEn: "Predestination",
        type: '电影',
        tags: ['悬疑', '科幻'],
        duration: '97 分钟',
        premiere: '2015-01-19',
        downloadLink: [
            {name: '电影天堂BD', downloadLink: 'https://www.dy2018.com/i/94200.html'},
        ],
        language: '英语',
        actors: ['伊桑·霍克' , '莎拉·斯努克' , '诺亚·泰勒' , '弗雷娅·斯塔福' , '伊莉斯·詹森'],
        doubanLink: 'https://movie.douban.com/subject/20278505/',
        comment: '悬疑，比较喜欢'
    },
    {
        cover: require('./covers/inception.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '盗梦空间',
        nameEn: "Inception",
        type: '电影',
        tags: ['剧情', '科幻', '悬疑', '动作'],
        duration: '148 分钟',
        premiere: '2010-09-01',
        downloadLink: [
            {name: '6V 1080p', downloadLink: 'http://www.6vhao.tv/dy6/2020-09-11/38905.html'},
        ],
        language: '英语',
        actors: ['莱昂纳多·迪卡普里奥' , '约瑟夫·高登-莱维特' , '艾利奥特·佩吉' , '汤姆·哈迪' , '渡边谦'],
        doubanLink: 'https://movie.douban.com/subject/3541415/',
        comment: '电影里程碑，诺兰！光看海报就热血沸腾'
    },
    {
        cover: require('./covers/interstellar.jpg'),
        wordTheme: 'white',
        position: 'right',
        name: '星际穿越',
        nameEn: "Interstellar",
        type: '电影',
        tags: ['剧情', '科幻'],
        duration: '169 分钟',
        premiere: '2014-11-12',
        downloadLink: [
            {name: '6V 1080p', downloadLink: 'http://www.6vhao.tv/dy6/2015-01-01/26406.html'},
        ],
        language: '英语',
        actors: ['马修·麦康纳' , '安妮·海瑟薇' , '杰西卡·查斯坦' , '麦肯吉·弗依' , '卡西·阿弗莱克'],
        doubanLink: 'https://movie.douban.com/subject/1889243/',
        comment: '让你切实的感受一下什么是相对论'
    },
    {
        cover: require('./covers/ford-v-ferrari.jpg'),
        wordTheme: 'white',
        position: 'left',
        name: '极速车王',
        nameEn: "Ford v Ferrari",
        type: '电影',
        tags: ['传记', '运动'],
        duration: '152 分钟',
        premiere: '2019-11-15',
        downloadLink: [
            {name: '电影港 1080p', downloadLink: 'https://www.dygang.tv/ys/20191231/43987.htm'},
        ],
        language: '英语',
        actors: ['马特·达蒙' , '克里斯蒂安·贝尔' , '乔什·卢卡斯' , '乔·博恩瑟' , '崔西·莱茨'],
        doubanLink: 'https://movie.douban.com/subject/6538866/',
        comment: '赛车就是爽，帅！带你了解勒芒24小时耐力赛'
    },
    {
        cover: require('./covers/spider-man-into-the-spider-verse.jpg'),
        wordTheme: 'black',
        position: 'right',
        name: '蜘蛛侠：平行宇宙',
        nameEn: "Spider-Man: Into the Spider-Verse",
        type: '电影',
        tags: ['动画'],
        duration: '116 分钟',
        premiere: '2018-12-14',
        downloadLink: [
            {name: '电影港 1080p', downloadLink: 'https://www.dygang.cc/dmq/20181228/41908.htm'},
        ],
        language: '英语',
        actors: ['沙梅克·摩尔' , '杰克·约翰逊' , '海莉·斯坦菲尔德' , '马赫沙拉·阿里' , '布莱恩·泰里·亨利'],
        doubanLink: 'https://movie.douban.com/subject/26374197/',
        comment: '相当爽的一部蜘蛛侠电影，大赞！独特的动画电影画风。'
    },
]
