export default [
    {
        title: '我的',
        icons: [
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/diary/' ,                       icon: require('./icons/logo-diary.png') ,        name: '日记' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/map/' ,                    icon: require('./icons/logo-map.png') ,          name: '路书' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/manager' ,                       icon: require('./icons/logo-manager.png') ,      name: '后台' ,       } ,
            { noPadding: false , isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/readme' ,                       icon: require('./icons/logo-doc.png') ,          name: 'README' ,   } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/me/gif' ,                       icon: require('./icons/logo-gif.gif') ,          name: '像素画' ,     },
            { noPadding: true ,  isNew: true,   isBgBlack: false,  pageLink: 'http://kylebing.cn/test/canvas-my-hole-life?v=1' , icon: require('./icons/logo-all-my-life.png') ,  name: '一生的时间' ,  },
        ]
    },
    {
        title: '工具',
        icons: [
            { noPadding: true ,  isNew: true,  isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/cbr650r' ,                  icon: require('./icons/logo-cbr650r.png') ,            name: 'CBR650R' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/car-oil' ,                 icon: require('./icons/logo-car-oil.png') ,            name: '汽车行程花费' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/qr?hash=two&from=kylebing.cn' ,  icon: require('./icons/logo-qr.png') ,                 name: '挪车提醒' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/name' ,                    icon: require('./icons/logo-name.png') ,               name: '起名工具' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/typepad' ,                 icon: require('./icons/logo-typepad.png') ,            name: '跟打器' ,      } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/keyboard/' ,               icon: require('./icons/logo-keyboard.png') ,           name: '键盘测试' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/calculator' ,              icon: require('./icons/logo-calculator.png') ,         name: '计算器' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/words' ,                   icon: require('./icons/logo-symbol.png') ,             name: '标点处理' ,     } ,
            // { noPadding: false , isNew: false, isBgBlack: false , pageLink: 'http://kylebing.cn/tools/vps' ,                     icon: require('./icons/logo-vps.png') ,                name: 'VPS' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/drop-and-show' ,           icon: require('./icons/logo-image-viewer.png') ,       name: '图片查看器' ,    } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/wubi-dict-editor-web' ,    icon: require('./icons/logo-wubi-editor.png') ,        name: '五笔助手' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/download' ,                      icon: require('./icons/logo-download.png') ,           name: '常用下载' ,     } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/unlock-music' ,            icon: require('./icons/logo-unlock-music.png') ,       name: '音乐解码' ,     } ,

        ]
    },
    {
        title: '开发工具',
        icons: [
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/json-table' ,           icon: require('./icons/logo-json-table.png') ,         name: '表格 JSON' ,  } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/useragent' ,            icon: require('./icons/logo-agent.png') ,              name: 'UserAgent' ,  } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/icons' ,                icon: require('./icons/logo-element-ui-icons.png') ,   name: 'element图标' , } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/base64-text' ,          icon: require('./icons/logo-base64.png') ,             name: 'Base64文本' , } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: 'http://kylebing.cn/e' ,                          icon: require('./icons/logo-ele.png') ,                name: 'Vue 例子'} ,
        ]
    },
    {
        title: 'Canvas',
        icons: [
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/tools/mine/' ,icon: require('./icons/logo-blank.png') ,name: '我的所有' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-lost/?isShowLine=0&titleFontSize=50&lineWidth=10&isShowTitle=1&bgColor=black&title=+++' ,icon: require('./icons/logo-web-canvas-lost.png') ,name: '迷离-+++' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-lost/?isShowLine=0&titleFontSize=50&lineWidth=10&isShowTitle=1&bgColor=black&title=HelloWorld' ,icon: require('./icons/logo-web-canvas-lost.png') ,name: '迷离-HW' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-lost/?isShowLine=0&titleFontSize=50&lineWidth=10&isShowTitle=1&bgColor=black&title=%E6%88%91' ,icon: require('./icons/logo-web-canvas-lost.png') ,name: '迷离-我' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-lost/?isShowLine=1&titleFontSize=50&lineWidth=10&isShowTitle=0' ,icon: require('./icons/logo-web-canvas-lost.png') ,name: '迷离-线条' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-lost' ,icon: require('./icons/logo-web-canvas-lost.png') ,name: '迷离' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-loading-canvas' ,icon: require('./icons/logo-web-canvas-loading.png') ,name: '圆圈' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-canvas-bg' ,     icon: require('./icons/logo-web-canvas-block.png') ,  name: '活动方块' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-heart-canvas' ,  icon: require('./icons/logo-web-canvas-heart.png') ,  name: '飘动的心' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-heart-canvas/?hMin=0&hMax=360&countHeart=500&sizeMin=10&sizeMax=50&bgColor=%233d3d3d' ,  icon: require('./icons/logo-web-canvas-heart.png') ,  name: '飘动的心' ,     } ,
            { noPadding: true ,  isNew: false,  isBgBlack: false,  pageLink: 'http://kylebing.cn/test/animate-bg-text-canvas' ,icon: require('./icons/logo-web-canvas-text.png') ,   name: '文字' ,     } ,
        ]
    },
    {
        title: '有趣的网站',
        icons: [
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.gsmarena.com/',                                          icon: require('./icons/logo-blank.png'),               name: '所有手机大全',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://neal.fun/design-the-next-iphone/',                           icon: require('./icons/logo-iphone.png'),               name: '我是库克',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://gallerix.asia/',                                             icon: require('./icons/logo-painting.png'),             name: '免费名画',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://dapanyuntu.com/',                                            icon: require('./icons/logo-stock.png'),                name: '大盘田字图',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://javier.xyz/emoji-to-scale',                                  icon: require('./icons/logo-emoji-scale.png'),          name: 'emoji排序',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.macosicongallery.com/',                                  icon: require('./icons/logo-macicon.png'),              name: 'Mac Icon',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.openstreetmap.org/',                                     icon: require('./icons/logo-openstreetmap.png'),        name: 'OpenStreetMap',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://oimo.io/works',                                              icon: require('./icons/logo-oimo.png'),                 name: 'oimo.io',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://hakim.se/',                                                  icon: require('./icons/logo-blank.png'),                name: 'hakim.se',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://kylebing.cn/tools/highway',                                  icon: require('./icons/logo-highway.png'),              name: '高速上的2B们',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.makemepulse.com/',                                       icon: require('./icons/logo-web-amazing.png'),          name: '页面效果哇塞',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://2017.makemepulse.com/',                                       icon: require('./icons/logo-web-amazing.png'),          name: '2017',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://2018.makemepulse.com/',                                       icon: require('./icons/logo-web-amazing.png'),          name: '2018',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://2019.makemepulse.com/',                                       icon: require('./icons/logo-web-amazing.png'),          name: '2019',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.v2ex.com/?r=kylebing',                                   icon: require('./icons/logo-web-v2ex.png'),             name: 'V2EX',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.shejipi.com/',                                           icon: require('./icons/logo-web-pi.png'),               name: '设计癖',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.chiphell.com/',                                          icon: require('./icons/logo-web-chiphell.png'),         name: 'chiphell', },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://iamthecu.be/',                                               icon: require('./icons/logo-web-cube.png'),             name: '魔方',       },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://neave.com/',                                                 icon: require('./icons/logo-web-neave.png'),            name: 'Neave',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://cabbi.bo/enough/',                                            icon: require('./icons/logo-web-cabbi.png'),            name: 'Cabbi',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://chrismckenzie.com/',                                         icon: require('./icons/logo-web-chrismckenzie.png'),    name: '小方块',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.omfgdogs.com/',                                          icon: require('./icons/logo-web-dogs.png'),             name: '欢乐小狗狗',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://patorjk.com/software/taag/#p=testall&f=Avatar&t=Kyle%20Bing', icon: require('./icons/logo-web-text-character.png'),   name: '字符字符',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://ps.gaoding.com/#/',                                          icon: require('./icons/logo-web-ps.png'),               name: '在线PS',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://how-i-experience-web-today.com/',                            icon: require('./icons/logo-web-webtoday.png'),         name: '今天的互联网',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://www.airpano.org.cn/360photo/china-1000island/',               icon: require('./icons/logo-web-360-view.png'),         name: '360中国千岛',  },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://izzyburton.co.uk/',                                          icon: require('./icons/logo-web-artist-ib.png'),        name: '艺术家IB',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://zoomquilt.org/',                                             icon: require('./icons/logo-web-pic-zoom.png'),         name: '不断放大图片',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://txti.es/',                                                    icon: require('./icons/logo-web-txti.png'),             name: '文字页面',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://pointerpointer.com/',                                        icon: require('./icons/logo-web-pointer.png'),          name: '点哪指哪',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://bruno-simon.com/',                                           icon: require('./icons/logo-web-racecar.png'),          name: '小赛车',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://greatestgifsofalltime.tumblr.com/',                          icon: require('./icons/logo-web-gif.gif'),              name: '唯美gif',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://chinesenewyear.net/',                                        icon: require('./icons/logo-web-chinese-new-year.png'), name: '中国年',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://cineshader.com/',                                            icon: require('./icons/logo-web-3d.png'),               name: '一个3D场景',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://theuselessweb.com/',                                         icon: require('./icons/logo-web-useless-website.png'),  name: '一堆无用站点',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://tympanus.net/Development/RainEffect/index.html#slide-4',     icon: require('./icons/logo-web-raining-outside.png'),  name: '窗外下雨了',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.noisli.com/',                                            icon: require('./icons/logo-web-noisli.png'),           name: '白嗓音',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://www.sinuousgame.com/',                                        icon: require('./icons/logo-web-game-avoid.png'),       name: '躲避游戏',      },
        ]
    },
]
