export default [
    {
        title: '我的',
        icons: [
            { noPadding: true ,  isNew: true,  isBgBlack: false,  pageLink: 'https://music.163.com/prime/m/gift-receive?d=XG_zS_50_j-DN-MTO9k9yA&p=p_E55KtdeJO5livvCYr0O0MVmIh2jJjC6hCeGii2oJbsch4o2sm8eUvEPzrLvf1QbpP_9B3Nz_vEHk0F_aHZidRNG8PC9VjwqL8u8IuPzto&userid=79759260&app_version=8.9.20&dlt=0846' ,                     icon: require('./icons/logo-netease-music.png') ,name: '7日黑胶(2月)' ,     } ,
            { noPadding: true ,  isNew: true,  isBgBlack: false,  pageLink: '../diary/' ,                     icon: require('./icons/logo-diary.png') ,        name: '日记' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../manager' ,                    icon: require('./icons/logo-manager.png') ,      name: '后台' ,       } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../readme' ,                     icon: require('./icons/logo-doc.png') ,          name: 'README' ,   } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../me/gif' ,                     icon: require('./icons/logo-gif.gif') ,          name: '像素画' ,      } ,
        ]
    },
    {
        title: '工具',
        icons: [
            { noPadding: false , isNew: true,  isBgBlack: false,  pageLink: '../tools/car-oil' ,              icon: require('./icons/logo-car-oil.png') ,            name: '汽车行程花费' ,      } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/name' ,                 icon: require('./icons/logo-name.png') ,               name: '起名工具' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../tools/typepad' ,              icon: require('./icons/logo-typepad.png') ,            name: '跟打器' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../qr/' ,                        icon: require('./icons/logo-qr.png') ,                 name: '挪车提醒' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/keyboard/' ,            icon: require('./icons/logo-keyboard.png') ,           name: '键盘测试' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/map/' ,                 icon: require('./icons/logo-map.png') ,                name: '地图工具' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/calculator' ,           icon: require('./icons/logo-calculator.png') ,         name: '计算器' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../tools/words' ,                icon: require('./icons/logo-symbol.png') ,             name: '标点处理' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/icons' ,                icon: require('./icons/logo-element-ui-icons.png') ,   name: 'element图标' , } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../tools/drop-and-show' ,        icon: require('./icons/logo-image-viewer.png') ,       name: '图片查看器' ,    } ,
            // { noPadding: false , isNew: false, isBgBlack: false , pageLink: '../tools/vps' ,                  icon: require('./icons/logo-vps.png') ,                name: 'VPS' ,      } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../e/#/base64/base64-text' ,     icon: require('./icons/logo-base64.png') ,             name: 'Base64工具' , } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../e' ,                          icon: require('./icons/logo-ele.png') ,                name: 'Vue 例子'} ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../tools/wubi-dict-editor-web' , icon: require('./icons/logo-wubi-editor.png') ,        name: '五笔助手' ,     } ,
            { noPadding: true ,  isNew: false, isBgBlack: false,  pageLink: '../download' ,                   icon: require('./icons/logo-download.png') ,           name: '常用下载' ,     } ,
            { noPadding: false , isNew: false, isBgBlack: false,  pageLink: '../tools/unlock-music' ,         icon: require('./icons/logo-unlock-music.png') ,       name: '音乐解码' ,     } ,
        ]
    },
    {
        title: '有趣的网站',
        icons: [
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.v2ex.com/?r=kylebing',                                   icon: require('./icons/logo-web-v2ex.png'),             name: 'V2EX',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.shejipi.com/',                                           icon: require('./icons/logo-web-pi.png'),               name: '设计癖',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.chiphell.com/',                                          icon: require('./icons/logo-web-chiphell.png'),         name: 'chiphell', },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://iamthecu.be/',                                               icon: require('./icons/logo-web-cube.png'),             name: '魔方',       },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://neave.com/',                                                 icon: require('./icons/logo-web-neave.png'),            name: 'Neave',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://cabbi.bo/enough/',                                            icon: require('./icons/logo-web-cabbi.png'),            name: 'Cabbi',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://chrismckenzie.com/',                                         icon: require('./icons/logo-web-chrismckenzie.png'),    name: '小方块',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.omfgdogs.com/',                                          icon: require('./icons/logo-web-dogs.png'),             name: '欢乐小狗狗',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://patorjk.com/software/taag/#p=testall&f=Avatar&t=Kyle%20Bing', icon: require('./icons/logo-web-text-character.png'),   name: '字符字符',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://ps.gaoding.com/#/',                                          icon: require('./icons/logo-web-ps.png'),               name: '在线PS',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://how-i-experience-web-today.com/',                            icon: require('./icons/logo-web-webtoday.png'),         name: '今天的互联网',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://www.airpano.org.cn/360photo/china-1000island/',               icon: require('./icons/logo-web-360-view.png'),         name: '360中国千岛',  },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://izzyburton.co.uk/',                                          icon: require('./icons/logo-web-artist-ib.png'),        name: '艺术家IB',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://zoomquilt.org/',                                             icon: require('./icons/logo-web-pic-zoom.png'),         name: '不断放大图片',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'http://txti.es/',                                                    icon: require('./icons/logo-web-txti.png'),             name: '文字页面',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://pointerpointer.com/',                                        icon: require('./icons/logo-web-pointer.png'),          name: '点哪指哪',     },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://bruno-simon.com/',                                           icon: require('./icons/logo-web-racecar.png'),          name: '小赛车',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://greatestgifsofalltime.tumblr.com/',                          icon: require('./icons/logo-web-gif.gif'),              name: '唯美gif',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.makemepulse.com/',                                       icon: require('./icons/logo-web-amazing.png'),          name: '页面效果哇塞',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://chinesenewyear.net/',                                        icon: require('./icons/logo-web-chinese-new-year.png'), name: '中国年',      },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://cineshader.com/',                                            icon: require('./icons/logo-web-3d.png'),               name: '一个3D场景',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://theuselessweb.com/',                                         icon: require('./icons/logo-web-useless-website.png'),  name: '一堆无用站点',   },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://tympanus.net/Development/RainEffect/index.html#slide-4',     icon: require('./icons/logo-web-raining-outside.png'),  name: '窗外下雨了',    },
            { noPadding: true, isNew: false, isBgBlack: false, pageLink: 'https://www.noisli.com/',                                            icon: require('./icons/logo-web-noisli.png'),           name: '白嗓音',      },
        ]
    },
]
